
name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ---
# name: "pre-release"
#
# on:
#   push:
#     branches:
#       - "master"
#
# jobs:
#   pre-release:
#     name: "Pre Release"
#     runs-on: "ubuntu-latest"
#     strategy:
#       matrix:
#         # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
#         goos: [linux, windows, darwin]
#         goarch: ["386", amd64, arm64]
#         exclude:
#           - goarch: "386"
#             goos: darwin
#           - goarch: arm64
#             goos: windows
#
#     steps:
#       - name: "Build"
#         run: |
#           go build -v -o eslint-git-diff
#
#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "latest"
#           prerelease: true
#           title: "Development Build"
#           files: |
#             eslint-git-diff
#             README.md
#
